// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Eye;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PersonRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface PersonRoot : GPBRootObject
@end

#pragma mark - Person

typedef GPB_ENUM(Person_FieldNumber) {
  Person_FieldNumber_Name = 1,
  Person_FieldNumber_EyeArray = 2,
};

@interface Person : GPBMessage

/// 个人名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/// Test to see if @c name has been set.
@property(nonatomic, readwrite) BOOL hasName;

///眼睛属性
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Eye*> *eyeArray;
/// The number of items in @c eyeArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger eyeArray_Count;

@end

#pragma mark - Eye

typedef GPB_ENUM(Eye_FieldNumber) {
  Eye_FieldNumber_Color = 1,
};

@interface Eye : GPBMessage

/// 眼睛颜色
@property(nonatomic, readwrite, copy, null_resettable) NSString *color;
/// Test to see if @c color has been set.
@property(nonatomic, readwrite) BOOL hasColor;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
